version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: lab_guide_container
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./docs/_build/html/:/usr/share/nginx/html
